# YAML is case sensitive - indentation of YAML is important
# use spaces, not tab
---
apiVersion: apps/v1 # which api to use for deployment
kind: Deployment # pod - service what kind of service/object you want to create
# What would you like to call it - name the service/object
metadata:
  name: nginx-deployment # naming the deployment
spec:
  selector:
    matchLabels:
      app: nginx # look for this label to match with k8 service
  # Let's create a replica set of this with instances/pods
  replicas: 3 # 3 pods
  # template to use its label for k8 service to launch in the browser
  template:
    metadata:
      labels:
        app: nginx # This label connects to the service or any other k8 components
    # Let's define the container spec
    spec:
      containers:
      - name: nginx
        image: ddoxton/tech241-nginx:latest # Use the image that I built
        ports:
        - containerPort: 100
          
