---
# Select the type of API version and type of service/object
apiVersion: v1
kind: Service
# Metadata for name
metadata:
  name: nginx-svc
  namespace: default #sre

# Specification to include ports selector to connect to the deployment
spec:
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 80

# Let's define the selector and label to connect to nginx deployment
  selector:
    app: nginx # this label connects this service to the deployment

# Creating NodePort type of deployment
  type: NodePort